import { 
  FaHome, 
  FaCompass, 
  FaImages, 
  FaBookmark, 
  FaCalendarAlt, 
  FaComments, 
  FaUsers, 
  FaFileAlt, 
  FaBlog, 
  FaNewspaper, 
  FaBriefcase, 
  FaEllipsisH 
} from 'react-icons/fa'

export const navigationItems = [
  {
    id: 'home',
    name: 'Home',
    path: '/',
    icon: FaHome,
    color: 'bg-blue-500',
  },
  {
    id: 'explore',
    name: 'Explore',
    path: '/explore',
    icon: FaCompass,
    color: 'bg-teal-500',
  },
  {
    id: 'albums',
    name: 'Albums',
    path: '/albums',
    icon: FaImages,
    color: 'bg-green-500',
  },
  {
    id: 'saved-posts',
    name: 'Saved Posts',
    path: '/saved-posts',
    icon: FaBookmark,
    color: 'bg-purple-500',
  },
  {
    id: 'events',
    name: 'Events',
    path: '/events',
    icon: FaCalendarAlt,
    color: 'bg-red-500',
  },
  {
    id: 'forum',
    name: 'Forum',
    path: '/forum',
    icon: FaComments,
    color: 'bg-yellow-500',
  },
  {
    id: 'my-groups',
    name: 'My Groups',
    path: '/my-groups',
    icon: FaUsers,
    color: 'bg-blue-400',
  },
  {
    id: 'my-pages',
    name: 'My Pages',
    path: '/my-pages',
    icon: FaFileAlt,
    color: 'bg-orange-500',
  },
  {
    id: 'blog',
    name: 'Blog',
    path: '/blog',
    icon: FaBlog,
    color: 'bg-red-400',
  },
  {
    id: 'article',
    name: 'Article',
    path: '/article',
    icon: FaNewspaper,
    color: 'bg-teal-400',
  },
  {
    id: 'jobs',
    name: 'Jobs',
    path: '/jobs',
    icon: FaBriefcase,
    color: 'bg-green-400',
  },
  {
    id: 'more',
    name: 'More',
    path: '/more',
    icon: FaEllipsisH,
    color: 'bg-pink-500',
  },
] 